const data = [
  {
    id: 1,
    Title: "De Beauchemp",
    Class: "rdebeauchemp0@nydailynews.com",
    Pricing: 9680,
  },
  { id: 2, Title: "Slingsby", Class: "aslingsby1@mashable.com", Pricing: 2712 },
  { id: 3, Title: "Dodridge", Class: "mdodridge2@nps.gov", Pricing: 7082 },
  { id: 4, Title: "Oxterby", Class: "loxterby3@goo.gl", Pricing: 4732 },
  { id: 5, Title: "Kliesl", Class: "ckliesl4@xinhuanet.com", Pricing: 6153 },
  { id: 6, Title: "Whitmell", Class: "cwhitmell5@jiathis.com", Pricing: 1959 },
  { id: 7, Title: "Glazyer", Class: "aglazyer6@123-reg.co.uk", Pricing: 9061 },
  {
    id: 8,
    Title: "Ramsdell",
    Class: "hramsdell7@reference.com",
    Pricing: 1938,
  },
  { id: 9, Title: "Schultes", Class: "aschultes8@nymag.com", Pricing: 1791 },
  {
    id: 10,
    Title: "Sapauton",
    Class: "rsapauton9@reference.com",
    Pricing: 5064,
  },
  { id: 11, Title: "Letson", Class: "mletsona@godaddy.com", Pricing: 4174 },
  { id: 12, Title: "Lazonby", Class: "wlazonbyb@cdc.gov", Pricing: 2907 },
  {
    id: 13,
    Title: "Dancey",
    Class: "ldanceyc@businessweek.com",
    Pricing: 1389,
  },
  { id: 14, Title: "Mertel", Class: "kmerteld@arizona.edu", Pricing: 9806 },
  { id: 15, Title: "Scurr", Class: "ascurre@google.de", Pricing: 6874 },
  {
    id: 16,
    Title: "Slay",
    Class: "gslayf@networkadvertising.org",
    Pricing: 7573,
  },
  {
    id: 17,
    Title: "Scrigmour",
    Class: "fscrigmourg@sfgate.com",
    Pricing: 2971,
  },
  { id: 18, Title: "Cawson", Class: "lcawsonh@mapy.cz", Pricing: 6633 },
  {
    id: 19,
    Title: "Dingate",
    Class: "adingatei@cargocollective.com",
    Pricing: 9308,
  },
  { id: 20, Title: "Dowden", Class: "edowdenj@1688.com", Pricing: 9946 },
  { id: 21, Title: "Dumbreck", Class: "ldumbreckk@upenn.edu", Pricing: 5889 },
  { id: 22, Title: "Polfer", Class: "lpolferl@weather.com", Pricing: 2451 },
  { id: 23, Title: "Maple", Class: "smaplem@twitpic.com", Pricing: 6656 },
  {
    id: 24,
    Title: "Nottingam",
    Class: "tnottingamn@yellowbook.com",
    Pricing: 6110,
  },
  { id: 25, Title: "Scammonden", Class: "cscammondeno@cdc.gov", Pricing: 5728 },
  { id: 26, Title: "Crocetti", Class: "lcrocettip@webs.com", Pricing: 5523 },
  { id: 27, Title: "le Keux", Class: "nlekeuxq@sbwire.com", Pricing: 3506 },
  { id: 28, Title: "Screech", Class: "rscreechr@a8.net", Pricing: 9021 },
  {
    id: 29,
    Title: "Shellshear",
    Class: "hshellshears@surveymonkey.com",
    Pricing: 1369,
  },
  {
    id: 30,
    Title: "Caunter",
    Class: "qcauntert@seattletimes.com",
    Pricing: 7639,
  },
  { id: 31, Title: "Kops", Class: "mkopsu@thetimes.co.uk", Pricing: 7429 },
  { id: 32, Title: "Ivashnyov", Class: "aivashnyovv@i2i.jp", Pricing: 1697 },
  { id: 33, Title: "Donnett", Class: "ydonnettw@youtube.com", Pricing: 7564 },
  {
    id: 34,
    Title: "Sanderson",
    Class: "tsandersonx@hubpages.com",
    Pricing: 1160,
  },
  { id: 35, Title: "Carnew", Class: "scarnewy@slate.com", Pricing: 6181 },
  { id: 36, Title: "Tovey", Class: "htoveyz@wikimedia.org", Pricing: 6200 },
  {
    id: 37,
    Title: "Josipovitz",
    Class: "djosipovitz10@foxnews.com",
    Pricing: 2857,
  },
  { id: 38, Title: "Orto", Class: "corto11@example.com", Pricing: 2410 },
  { id: 39, Title: "Kapelhof", Class: "ckapelhof12@abc.net.au", Pricing: 4824 },
  { id: 40, Title: "Rillstone", Class: "mrillstone13@hp.com", Pricing: 2230 },
  { id: 41, Title: "Pithcock", Class: "spithcock14@tmall.com", Pricing: 4391 },
  { id: 42, Title: "Giraudeau", Class: "rgiraudeau15@gnu.org", Pricing: 5968 },
  {
    id: 43,
    Title: "Coward",
    Class: "ecoward16@theguardian.com",
    Pricing: 5164,
  },
  { id: 44, Title: "Bunson", Class: "vbunson17@multiply.com", Pricing: 5128 },
  { id: 45, Title: "Dafter", Class: "cdafter18@slashdot.org", Pricing: 1281 },
  { id: 46, Title: "Wolverson", Class: "jwolverson19@ihg.com", Pricing: 1515 },
  { id: 47, Title: "Pilgrim", Class: "vpilgrim1a@pbs.org", Pricing: 2324 },
  { id: 48, Title: "Godbehere", Class: "jgodbehere1b@who.int", Pricing: 6029 },
  
];

export default data